apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: model-routing-policy
  namespace: llm-d-precise-prefix-gw
  labels:
    app: model-routing
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: llm-d-inference-gateway
  traffic:
    phase: PreRouting
    transformation:
      request:
        set:
          - name: X-Gateway-Base-Model-Name
            value: |
              {
                "qwen25-7b-instruct": "qwen25-7b-instruct",
                "glm-4-9b": "glm-4-9b"
              }[string(json(request.body).model)]
